
----------------------------------------
-- 1. 테이블 스페이스 및 계정 생성 
----------------------------------------

-- 테이블 스페이스 생성

CREATE TABLESPACE SQLSTUDY_DATA
DATAFILE 'SQLSTUDY2022_DATA.dbf' SIZE 4G
AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
;

-- 임시 테이블 스페이스 생성

CREATE TEMPORARY TABLESPACE SQLSTUDY_TMP
TEMPFILE 'SQLSTUDY2022_TMP.dbf' SIZE 1G
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
;

-- 테이블스페이스 위치 확인

SELECT	*
FROM 	DBA_DATA_FILES
;

-- 사용자 계정 생성

CREATE USER SQLSTUDY2022 IDENTIFIED BY SQLSTUDY2022
DEFAULT TABLESPACE SQLSTUDY_DATA
TEMPORARY TABLESPACE SQLSTUDY_TMP
PROFILE DEFAULT
ACCOUNT UNLOCK
;

-- 계정에 권한 주기

GRANT RESOURCE TO SQLSTUDY2022;
GRANT CONNECT TO SQLSTUDY2022;
GRANT CREATE VIEW TO SQLSTUDY2022;
GRANT CREATE SYNONYM TO SQLSTUDY2022;

-- 계정 조회

SELECT	*
FROM 	ALL_USERS
;

----------------------------------------
-- 2. 실습 테이블 구성을 위해 알아두어야 할 것.
----------------------------------------

-- 계층형 쿼리 사용 

SELECT  *
FROM    DUAL
CONNECT BY LEVEL <= 1000
;

-- 랜덤 숫자 조회

SELECT	TRUNC(DBMS_RANDOM.VALUE(1, 100))
FROM 	DUAL
;

-- 랜덤 문자열 조회

SELECT	DBMS_RANDOM.STRING('U', 10)
FROM	DUAL
;

